tap "homebrew/dupes"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/bundle"
tap "homebrew/services"
tap "justwatchcom/gopass"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
brew "python3"
brew "awscli"
brew "bash"
brew "cmake"
brew "coreutils"
brew "dnsmasq", restart_service: true
brew "entr"
brew "exa"
brew "lame"
brew "git"
brew "ffmpeg"
brew "findutils"
brew "fish"
brew "fzf"
brew "jpeg"
brew "git-flow"
brew "gopass"
brew "graphicsmagick"
brew "graphviz", args: ["with-pango"]
brew "grep"
brew "highlight"
brew "hub"
brew "imagemagick"
brew "python"
brew "macvim"
brew "mariadb"
brew "mas"
brew "nginx", restart_service: true
brew "node"
brew "postgresql"
brew "ripgrep"
brew "rust"
brew "streamlink"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "homebrew/php/composer"
brew "homebrew/php/php71"
cask "anaconda"
cask "discord"
cask "gimp"
cask "iterm2"
cask "macvim"
cask "mysqlworkbench"
cask "openemu"
cask "postico"
cask "postman"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "sequel-pro"
cask "streamlink-twitch-gui"
cask "the-unarchiver"
cask "vagrant"
cask "vimr"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vlc"
cask "youtube-to-mp3"
cask "caskroom/fonts/font-iosevka"
cask "caskroom/versions/transmit4"
mas "GravitDesigner", id: 1207744923
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Textual", id: 896450579
mas "Xcode", id: 497799835
